src/Acme.SaleProject.Web/Pages/Customers/CreateModal.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using Acme.SaleProject.Customers;
using System.Collections.Generic;
using Volo.Abp.Domain.Repositories;
using Volo.Abp.Users;
using System;

namespace Acme.SaleProject.Web.Pages.Customers
{
    public class CreateModalModel : SaleProjectPageModel
    {
        [BindProperty]
        public CreateUpdateCustomerDto Customer { get; set; }

        private readonly CustomerAppService _customerAppService;
        public CreateModalModel(CustomerAppService bookAppService)
        {
            _customerAppService = bookAppService;
        }

        public void OnGet()
        {
            Customer = new CreateUpdateCustomerDto();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            await _customerAppService.CreateAsync(Customer);
            return NoContent();
        }
    }
}

src/Acme.SaleProject.Web/Pages/Customers/EditModal.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using System;
using Acme.SaleProject.Customers;
using Volo.Abp.Users;
using DocumentFormat.OpenXml.Office2010.ExcelAc;
using System.Collections.Generic;
using Volo.Abp.Domain.Repositories;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Acme.SaleProject.Web.Pages.Customers
{
    public class EditModalModel : SaleProjectPageModel
    {
        [HiddenInput]
        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }

        [BindProperty]
        public CreateUpdateCustomerDto Customer { get; set; }
        private readonly CustomerAppService _customerAppService;
        private readonly IRepository<History> _myEntityRepository;
        public EditModalModel(CustomerAppService customerAppService, IRepository<History> myEntityRepository)
        {
            _customerAppService = customerAppService;
            _myEntityRepository = myEntityRepository;
        }
        public async Task OnGetAsync()
        {
            var customerDto = await _customerAppService.GetAsync(Id);
            Customer = ObjectMapper.Map<CustomerDto, CreateUpdateCustomerDto>(customerDto);
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var customerDto = await _customerAppService.GetAsync(Id);
            await _customerAppService.UpdateAsync(Id, Customer);

            if (customerDto.Status != Customer.Status)
                WriteToHistory();
            
            return NoContent();
        }
        public async Task<IActionResult> WriteToHistory()
        {
            //initialization new History
            History history = new History();

            history.Name = Customer.Name;
            history.NumberPhone = Customer.NumberPhone;
            history.ProcessDate = DateTime.Now;
            history.ProcessBy = CurrentUser.UserName; //current user is changing status
            history.Status = Customer.Status;
            //Insert into history db
            await _myEntityRepository.InsertAsync(history);
            return NoContent();
        }
    }
}

src/Acme.SaleProject.Web/Pages/Customers/ExcelModal.cshtml.cs
using Acme.SaleProject.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using Volo.Abp.Domain.Repositories;
using ClosedXML.Excel;
using System;
using Microsoft.AspNetCore.Http;
using System.Threading.Tasks;

namespace Acme.SaleProject.Web.Pages.Customers
{
    public class ExcelModalModel : SaleProjectPageModel
    {
        private readonly IRepository<Customer> _myEntityRepository;
        public CreateUpdateCustomerDto Customer { get; set; }
        public ExcelModalModel(IRepository<Customer> myEntityRepository)
        {
            _myEntityRepository = myEntityRepository;
        }
        public void OnGet()
        {
            Customer = new CreateUpdateCustomerDto();
        }
        public CustomerStatus GetStatusbyName(string name)
        {
            //Default is NotContactedYet
            CustomerStatus status = CustomerStatus.NotContactedYet;
            foreach (CustomerStatus item in Enum.GetValues(typeof(CustomerStatus)))
            {
                if (item.ToString() == name)
                {
                    status = item;
                }
            }
            return status; 
        }
        public Task<IActionResult> OnPostImportAsync(IFormFile excel)
        {
            List<Customer> list = new List<Customer>();

            using (var workbook = new XLWorkbook(excel.OpenReadStream()))
            {
                var worksheet = workbook.Worksheet("Sheet1");

                var count = 0;
                foreach (var row in worksheet.Rows())
                {
                    count += 1;
                    if (count > 1 && (row.Cell(1).Value.ToString() != null || row.Cell(1).Value.ToString() != string.Empty))
                    {
                        list.Add(new Customer
                        {
                            Name = row.Cell(1).Value.ToString(),
                            NumberPhone = row.Cell(2).Value.ToString(),
                            Address = row.Cell(3).Value.ToString(),
                            Status = GetStatusbyName(row.Cell(4).Value.ToString()),
                        });
                    }
                }
                UpdateDB(list);
            }
            return Task.FromResult<IActionResult>(Page());
        }
        public async Task<IActionResult> UpdateDB(List<Customer> customer)
        {
            await _myEntityRepository.InsertManyAsync(customer);
            return NoContent();
        }
    }
}

src/Acme.SaleProject.Web/Pages/Customers/History.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Acme.SaleProject.Web.Pages.Customers
{
    public class HistoryModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Acme.SaleProject.Web/Pages/Customers/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Acme.SaleProject.Web.Pages.Customers
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

src/Acme.SaleProject.Web/Pages/Customers/Order.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using System;
using Acme.SaleProject.Customers;
using Volo.Abp.Users;
using DocumentFormat.OpenXml.Office2010.ExcelAc;
using System.Collections.Generic;
using Volo.Abp.Domain.Repositories;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.JSInterop;
using DocumentFormat.OpenXml.Bibliography;


namespace Acme.SaleProject.Web.Pages.Customers
{
    public class OrderModel : SaleProjectPageModel
    {
        [HiddenInput]
        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }
        public int SelectedItemId { get; set; }
        public string TextSelect { get; set; }
        public List<SelectListItem> DropdownList { get; set; }
        public string CustomerName { get; set; }

        [BindProperty]
        public string Name { get; set; }

        [BindProperty]
        public string Price { get; set; }

        [BindProperty]
        public string Description { get; set; }

        [BindProperty]
        public string TotalAmout { get; set; }

        private readonly CustomerAppService _customerAppService;
        private readonly IRepository<History> _myEntityRepository;
        public OrderModel(CustomerAppService customerAppService, IRepository<History> myEntityRepository)
        {
            _customerAppService = customerAppService;
            _myEntityRepository = myEntityRepository;
        }
        public async Task OnGetAsync()
        {
            DropdownList = new List<SelectListItem>()
            {
                new SelectListItem() { Value = "10.9", Text = "Shoe" },
                new SelectListItem() { Value = "9.5", Text = "Hat" },
                new SelectListItem() { Value = "6.99", Text = "Jeans" }
            };

            var customerDto = await _customerAppService.GetAsync(Id);
            CustomerName = customerDto.Name;
        }
        public async Task<IActionResult> OnPostHandleDataAsync()
        {
            var customerDto = await _customerAppService.GetAsync(Id);

            //initialization new History
            History history = new History();

            history.Name = customerDto.Name;
            history.NumberPhone = customerDto.NumberPhone;
            history.ProcessDate = DateTime.Now;
            history.ProcessBy = CurrentUser.UserName; //current user is changing status
            history.Status = customerDto.Status;
            history.ProductName = Request.Form["TextSelect"].ToString();
            history.Description = Request.Form["Description"].ToString();
            history.Price = float.Parse(Request.Form["Price"].ToString());
            history.Quantity = int.Parse(Request.Form["Quantity"].ToString());
            history.TotalAmount = float.Parse(Request.Form["TotalAmount"].ToString());
            //Insert into history db
            await _myEntityRepository.InsertAsync(history);
            return NoContent();
            return NoContent();
        }
        //public async Task OnGetAsync()
        //{
        //    var customerDto = await _customerAppService.GetAsync(Id);
        //    OrderDto = new CreateOrderDto();

        //    MyOptions = new List<SelectListItem>
        //    {
        //        new SelectListItem { Value = "Shoe - 10$", Text = "Shoe - 10$" },
        //        new SelectListItem { Value = "Nintendo - 5.5$", Text = "Nintendo - 5.5$" },
        //        new SelectListItem { Value = "Xbox One - 4.9$", Text = "Xbox One - 4.9$" }
        //    };
        //}

        //public async Task<IActionResult> OnPostAsync()
        //{          
        //    return NoContent();
        //}
        //public async Task<IActionResult> WriteToHistory()
        //{
        //    var customerDto = await _customerAppService.GetAsync(Id);
        //    //initialization new History
        //    History history = new History();

        //    history.Name = customerDto.Name;
        //    history.NumberPhone = customerDto.NumberPhone;
        //    history.ProcessDate = DateTime.Now;
        //    history.ProcessBy = CurrentUser.UserName; //current user is changing status
        //    history.Status = customerDto.Status;
        //    history.ProductName = Request.Form["SelectedItemId"].ToString();
        //    history.Description = Request.Form["Description"].ToString();
        //    history.Price = float.Parse(Request.Form["Price"].ToString());
        //    history.Quantity = int.Parse(Request.Form["Quantity"].ToString());
        //    history.TotalAmount = float.Parse(Request.Form["TotalAmount"].ToString()); 
        //    //Insert into history db
        //    await _myEntityRepository.InsertAsync(history);
        //    return NoContent();
        //}
    }
}

src/Acme.SaleProject.Web/Pages/Customers/ViewMore.cshtml.cs
using Acme.SaleProject.Customers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;
using System;
using Volo.Abp.Domain.Repositories;

namespace Acme.SaleProject.Web.Pages.Customers
{
    public class ViewMoreModel : SaleProjectPageModel
    {
        [HiddenInput]
        [BindProperty(SupportsGet = true)]
        public Guid Id { get; set; }

        [BindProperty]
        public HistoryDto historyDto { get; set; }
        private readonly HistoryAppService _customerAppService;
        public ViewMoreModel(HistoryAppService customerAppService)
        {
            _customerAppService = customerAppService;
        }
        public async Task OnGetAsync()
        {
            historyDto = await _customerAppService.GetAsync(Id);
        }
    }
}

src/Acme.SaleProject.Web/Pages/Customers/CreateModal.cshtml
@page
@using Microsoft.Extensions.Localization
@using Acme.SaleProject.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@using Acme.SaleProject.Web.Pages.Customers

@model CreateModalModel
@inject IStringLocalizer<SaleProjectResource> L
@{
    Layout = null;
}
<abp-dynamic-form abp-model="Customer" asp-page="/Customers/CreateModal">
    <abp-modal>
        <abp-modal-header title="@L["NewCustomer"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-form-content />
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</abp-dynamic-form>

src/Acme.SaleProject.Web/Pages/Customers/EditModal.cshtml
@page
@using Microsoft.Extensions.Localization
@using Acme.SaleProject.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@using Acme.SaleProject.Web.Pages.Customers

@model EditModalModel
@inject IStringLocalizer<SaleProjectResource> L
@{
    Layout = null;
}
<abp-dynamic-form abp-model="Customer" asp-page="/Customers/EditModal">
    <abp-modal>
        <abp-modal-header title="@L["UpdateProfile"].Value"></abp-modal-header>
        <abp-modal-body>
            <abp-input asp-for="Id" />
            <abp-form-content />
        </abp-modal-body>
        <abp-modal-footer buttons="@(AbpModalButtons.Cancel|AbpModalButtons.Save)"></abp-modal-footer>
    </abp-modal>
</abp-dynamic-form>

src/Acme.SaleProject.Web/Pages/Customers/ExcelModal.cshtml
@page
@using Microsoft.Extensions.Localization
@using Acme.SaleProject.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@using Acme.SaleProject.Web.Pages.Customers

@model ExcelModalModel
@inject IStringLocalizer<SaleProjectResource> L
@{
    Layout = null;
}
<abp-modal>
    <abp-modal-header title="@L["ImportExcel"].Value"></abp-modal-header>
    <abp-modal-body>
        <form method="POST" enctype="multipart/form-data" asp-page-handler="Import">
            <input type="file" name="excel" />
            <abp-button button-type="Primary" type="Submit">Import Data</abp-button>
        </form>
    </abp-modal-body>
</abp-modal>

src/Acme.SaleProject.Web/Pages/Customers/History.cshtml
@page
@using Acme.SaleProject.Localization
@using Acme.SaleProject.Web.Pages.Customers
@using Microsoft.Extensions.Localization
@model HistoryModel
@inject IStringLocalizer<SaleProjectResource> L
@section scripts
{
    <abp-script src="/Pages/Customers/History.js" />
}
<abp-card>
    <abp-card-header>
        <abp-row>
            <abp-column size-md="_6">
                <abp-card-title>Order history</abp-card-title>
            </abp-column>
        </abp-row>
    </abp-card-header>
    <abp-card-body>
        <abp-table striped-rows="true" id="HistoryTable"></abp-table>
    </abp-card-body>
</abp-card>

src/Acme.SaleProject.Web/Pages/Customers/Index.cshtml
@page
@using Acme.SaleProject.Localization
@using Acme.SaleProject.Web.Pages.Customers
@using Microsoft.Extensions.Localization
@model IndexModel
@inject IStringLocalizer<SaleProjectResource> L
@section scripts
    {
    <abp-script src="/Pages/Customers/Index.js" />
}
<abp-card>
    <abp-card-header>
        <abp-row>
            <abp-column size-md="_6">
                <abp-card-title>@L["Customers"]</abp-card-title>
            </abp-column>
            <abp-column size-md="_6" class="text-end">
                <abp-button id="NewCustomerButton"
                            text="@L["NewCustomer"].Value"
                            icon="plus"
                            button-type="Primary" />
                <abp-button id="ImportExcel"
                            text="@L["ImportExcel"].Value"
                            icon="plus"
                            button-type="Primary" />
            </abp-column>
        </abp-row>
    </abp-card-header>
    <abp-card-body>
        <abp-table striped-rows="true" id="CustomersTable"></abp-table>
    </abp-card-body>
</abp-card>

src/Acme.SaleProject.Web/Pages/Customers/Order.cshtml
@page
@using Microsoft.Extensions.Localization
@using Acme.SaleProject.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@using Acme.SaleProject.Web.Pages.Customers

@model OrderModel
@inject IStringLocalizer<SaleProjectResource> L
@{
    Layout = null;
}

<abp-modal>
    <abp-modal-header title="@Model.CustomerName"></abp-modal-header>
    <abp-modal-body>
        <form method="POST" enctype="multipart/form-data" asp-page-handler="HandleData">
            <abp-input asp-for="Id" />
            <div class="mb-3">
                <label for="product" class="form-label">Product:</label>
                <select asp-for="SelectedItemId" asp-items="Model.DropdownList" class="form-control"></select>
            </div>
            <input type="hidden" asp-for="TextSelect" />
            <div class="mb-3">
                <label for="description" class="form-label">Description:</label>
                <input type="text" id="description" name="Description" value="@Model.Description" class="form-control valid" />
            </div>
            <div class="mb-3">
                <label for="amount">Price:</label>
                <input type="text" id="price" name="Price" value="@Model.Price" class="form-control valid" readonly />
            </div>
            <div class="mb-3">
                <label for="quantity">Quantity:</label>
                <input type="number" id="quantity" name="Quantity" min="1" value="1" class="form-control valid" />
            </div>
            <div class="mb-3">
                <label for="totalAmout">Total Amount ($):</label>
                <input type="text" id="totalAmount" name="TotalAmount" value="@Model.TotalAmout" class="form-control valid" readonly />
            </div>
            <div class="mb-3" style="text-align: center">
                <abp-button button-type="Primary" type="Submit">Submit</abp-button>
            </div>
        </form>
    </abp-modal-body>
</abp-modal>
<script>
    $(document).ready(function () {
        var quantityInput = document.getElementById('quantity');
        var priceInput = document.getElementById('price');
        var totalAmountInput = document.getElementById('totalAmount');
        var productPrice = document.getElementById("SelectedItemId").value;

        //Set price and total amount
        priceInput.value = productPrice;
        updateTotalAmount();

        document.getElementById("SelectedItemId").addEventListener("change", function () {
            var productPrice = document.getElementById("SelectedItemId").value;
            document.getElementById("price").value = productPrice;

            var selectElement = document.getElementById("SelectedItemId");
            var selectedOption = selectElement.options[selectElement.selectedIndex];
            document.getElementById("TextSelect").value = selectedOption.text;
        });



        quantityInput.addEventListener('input', function () {
            updateTotalAmount();
        });

        priceInput.addEventListener('input', function () {
            updateTotalAmount();
        });

        function updateTotalAmount() {
            var quantity = parseFloat(quantityInput.value);
            var price = parseFloat(priceInput.value);
            var totalAmount = quantity * price;

            totalAmountInput.value = totalAmount.toFixed(2);;
        }
    });
</script>

src/Acme.SaleProject.Web/Pages/Customers/ViewMore.cshtml
@page
@using Microsoft.Extensions.Localization
@using Acme.SaleProject.Localization
@using Volo.Abp.AspNetCore.Mvc.UI.Bootstrap.TagHelpers.Modal
@using Acme.SaleProject.Web.Pages.Customers

@model ViewMoreModel
@inject IStringLocalizer<SaleProjectResource> L
@{
    Layout = null;
}
<style>
    .container {
        display: flex;
        flex-wrap: wrap;
    }

    .item {
        flex-basis: 50%;
        padding: 10px;
        box-sizing: border-box;
        font-weight: bold;
        color: black;
    }

    .itemChild {
        flex-basis: 50%;
        padding: 10px;
        box-sizing: border-box;
        color: #333;
    }

    .container div
    {
        border-bottom: 1px solid gray;
    }

</style>
<abp-modal>
    <abp-modal-header title="@L["ViewMore"].Value"></abp-modal-header>
    <abp-modal-body>
        <abp-input asp-for="Id" />
        <div class="container">
            <div class="item">Name</div>
            <div class="itemChild">@Model.historyDto.Name</div>

            <div class="item">Product Name</div>
            <div class="itemChild">@Model.historyDto.ProductName</div>

            <div class="item">Price</div>
            <div class="itemChild">@Model.historyDto.Price $</div>

            <div class="item">Description</div>
            <div class="itemChild">@Model.historyDto.Description</div>

            <div class="item">Quantity</div>
            <div class="itemChild">@Model.historyDto.Quantity</div>

            <div class="item">Total Amount</div>
            <div class="itemChild">@Model.historyDto.TotalAmount $</div>

            <div class="item">Number Phone</div>
            <div class="itemChild">@Model.historyDto.NumberPhone</div>

            <div class="item">Status</div>
            <div class="itemChild">@Model.historyDto.Status</div>

            <div class="item">Process By</div>
            <div class="itemChild">@Model.historyDto.ProcessBy</div>

            <div class="item">Process Date</div>
            <div class="itemChild">@Model.historyDto.ProcessDate</div>
        </div>
    </abp-modal-body>
    <abp-modal-footer buttons="@AbpModalButtons.Cancel"></abp-modal-footer>
</abp-modal>